name: Optimize resource pack
on: [push, workflow_dispatch]

jobs:
  packsquash:
    permissions: write-all
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          # The "options" field is TOML â€” must start at column 0
          options: |
            pack_directory = "."
            output_file_path = "./pack.zip"

            [[texture_overrides]]
            path = "assets/mcicore/**"
            optimize = false

            [[texture_overrides]]
            path = "pack.png"
            optimize = false

      - name: Generate Hash
        run: sha1sum pack.zip | head -c 40 > hash.txt

      - name: Copy Pack For Plugin
        run: cp pack.zip $(cat hash.txt).zip

      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            *.zip
            hash.txt
